filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/app_logs/app.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.template.enabled: true
setup.ilm.enabled: false
output.elasticsearch.pipeline: phase2_log_parser


